version: '3'

services:
  eip_scanner:
    build: .
    volumes:
      - .:/code
    command: test/cli_test
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
    depends_on:
      - opener_adapter

  opener_adapter:
    build: Dockers/opener
    working_dir: /OpENer/bin/posix/src/ports/POSIX
    command: ./OpENer eth0
    ports:
      - "44818:44818"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  gdbserver:
    build:
      context: Dockers/gdbserver
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "7776:22"
      - "7777:7777"
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16